name: Build and Upload APK

on:
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'  # 设置为 Java 11
          distribution: 'zulu'  # 指定 Java 发行版，解决 distribution 错误

      - name: Set up NDK
        run: |
          # 下载并安装 NDK
          mkdir -p $HOME/ndk
          wget https://dl.google.com/android/repository/android-ndk-r21e-linux-x86_64.zip -O $HOME/ndk/ndk.zip
          unzip -q $HOME/ndk/ndk.zip -d $HOME/ndk
          
          # 配置 local.properties 文件，添加 NDK 路径
          echo "ndk.dir=$HOME/ndk/android-ndk-r21e" >> $GITHUB_WORKSPACE/local.properties

      - name: Set up Gradle
        uses: gradle/wrapper-validation-action@v1

      - name: Grant Execute Permission to gradlew
        run: chmod +x ./gradlew  # 给 gradlew 脚本授予执行权限

      - name: Build APK
        run: ./gradlew assembleRelease -Darch=arm64

      - name: Upload APK to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'FCL/build/outputs/apk/release/*.apk'  # 构建输出的 APK 文件路径
          token: ${{ secrets.GITHUB_TOKEN }}